version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_HOST: localhost
    ports:
      - 33019:3306
    networks:
      - kaistnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - kaistnet
    depends_on:
      - db
    links:
      - db

  # web:
  #   image: gradle:8.4.0-jdk17
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   entrypoint: ["echo", "Hello World!"]
  #   ports:
  #     - 8091:8091
  #   networks:
  #     - kaistnet
  #   depends_on:
  #     - db
  #   links:
  #     - db

networks:
  kaistnet:
    driver: bridge
